# Generated by Django 5.2.3 on 2025-06-25 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_matcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
