# Generated by Django 5.2.3 on 2025-06-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_matcher', '0002_resume_file_resume_parsed_text_alter_resume_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
